/* tslint:disable */
/* eslint-disable */
/**
 * Our Game Api
 * Api calls and message processing functions for the Our Game app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdjustmentType
 */
export interface AdjustmentType {
    /**
     * 
     * @type {string}
     * @memberof AdjustmentType
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AdjustmentType
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof AdjustmentType
     */
    description?: string;
}

/**
 * Check if a given object implements the AdjustmentType interface.
 */
export function instanceOfAdjustmentType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AdjustmentTypeFromJSON(json: any): AdjustmentType {
    return AdjustmentTypeFromJSONTyped(json, false);
}

export function AdjustmentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdjustmentType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function AdjustmentTypeToJSON(value?: AdjustmentType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'description': value.description,
    };
}

