/* tslint:disable */
/* eslint-disable */
/**
 * Our Game Api
 * Api calls and message processing functions for the Our Game app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FixtureOfficialAppointment } from './FixtureOfficialAppointment';
import {
    FixtureOfficialAppointmentFromJSON,
    FixtureOfficialAppointmentFromJSONTyped,
    FixtureOfficialAppointmentToJSON,
} from './FixtureOfficialAppointment';

/**
 * 
 * @export
 * @interface OfficialType
 */
export interface OfficialType {
    /**
     * 
     * @type {string}
     * @memberof OfficialType
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficialType
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficialType
     */
    description?: string;
    /**
     * 
     * @type {Array<FixtureOfficialAppointment>}
     * @memberof OfficialType
     */
    fixtureOfficialAppointments?: Array<FixtureOfficialAppointment>;
}

/**
 * Check if a given object implements the OfficialType interface.
 */
export function instanceOfOfficialType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OfficialTypeFromJSON(json: any): OfficialType {
    return OfficialTypeFromJSONTyped(json, false);
}

export function OfficialTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfficialType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fixtureOfficialAppointments': !exists(json, 'fixtureOfficialAppointments') ? undefined : ((json['fixtureOfficialAppointments'] as Array<any>).map(FixtureOfficialAppointmentFromJSON)),
    };
}

export function OfficialTypeToJSON(value?: OfficialType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'description': value.description,
        'fixtureOfficialAppointments': value.fixtureOfficialAppointments === undefined ? undefined : ((value.fixtureOfficialAppointments as Array<any>).map(FixtureOfficialAppointmentToJSON)),
    };
}

