/* tslint:disable */
/* eslint-disable */
/**
 * Our Game Api
 * Api calls and message processing functions for the Our Game app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
} from './Venue';

/**
 * 
 * @export
 * @interface VenueType
 */
export interface VenueType {
    /**
     * 
     * @type {string}
     * @memberof VenueType
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueType
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof VenueType
     */
    description?: string;
    /**
     * 
     * @type {Array<Venue>}
     * @memberof VenueType
     */
    venues?: Array<Venue>;
}

/**
 * Check if a given object implements the VenueType interface.
 */
export function instanceOfVenueType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VenueTypeFromJSON(json: any): VenueType {
    return VenueTypeFromJSONTyped(json, false);
}

export function VenueTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'venues': !exists(json, 'venues') ? undefined : ((json['venues'] as Array<any>).map(VenueFromJSON)),
    };
}

export function VenueTypeToJSON(value?: VenueType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'description': value.description,
        'venues': value.venues === undefined ? undefined : ((value.venues as Array<any>).map(VenueToJSON)),
    };
}

