/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { DataApi } from './DataApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AdjustmentTypes } from './models/AdjustmentTypes';
export type { AdjustmentTypes_NoAutoPK } from './models/AdjustmentTypes_NoAutoPK';
export type { AdjustmentTypes_NoPK } from './models/AdjustmentTypes_NoPK';
export type { Associations } from './models/Associations';
export type { Associations_NoAutoPK } from './models/Associations_NoAutoPK';
export type { Associations_NoPK } from './models/Associations_NoPK';
export type { AssociationStaffs } from './models/AssociationStaffs';
export type { AssociationStaffs_NoAutoPK } from './models/AssociationStaffs_NoAutoPK';
export type { AssociationStaffs_NoPK } from './models/AssociationStaffs_NoPK';
export type { AssociationStaffTypes } from './models/AssociationStaffTypes';
export type { AssociationStaffTypes_NoAutoPK } from './models/AssociationStaffTypes_NoAutoPK';
export type { AssociationStaffTypes_NoPK } from './models/AssociationStaffTypes_NoPK';
export type { AssociationTeams } from './models/AssociationTeams';
export type { AssociationTeams_NoAutoPK } from './models/AssociationTeams_NoAutoPK';
export type { AssociationTeams_NoPK } from './models/AssociationTeams_NoPK';
export type { Clubs } from './models/Clubs';
export type { Clubs_NoAutoPK } from './models/Clubs_NoAutoPK';
export type { Clubs_NoPK } from './models/Clubs_NoPK';
export type { Competitions } from './models/Competitions';
export type { Competitions_NoAutoPK } from './models/Competitions_NoAutoPK';
export type { Competitions_NoPK } from './models/Competitions_NoPK';
export type { CompetitionSeasons } from './models/CompetitionSeasons';
export type { CompetitionSeasons_NoAutoPK } from './models/CompetitionSeasons_NoAutoPK';
export type { CompetitionSeasons_NoPK } from './models/CompetitionSeasons_NoPK';
export type { CompetitionTypes } from './models/CompetitionTypes';
export type { CompetitionTypes_NoAutoPK } from './models/CompetitionTypes_NoAutoPK';
export type { CompetitionTypes_NoPK } from './models/CompetitionTypes_NoPK';
export type { FixtureEvents } from './models/FixtureEvents';
export type { FixtureEvents_NoAutoPK } from './models/FixtureEvents_NoAutoPK';
export type { FixtureEvents_NoPK } from './models/FixtureEvents_NoPK';
export type { FixtureOfficialAppointments } from './models/FixtureOfficialAppointments';
export type { FixtureOfficialAppointments_NoAutoPK } from './models/FixtureOfficialAppointments_NoAutoPK';
export type { FixtureOfficialAppointments_NoPK } from './models/FixtureOfficialAppointments_NoPK';
export type { FixturePlayers } from './models/FixturePlayers';
export type { FixturePlayers_NoAutoPK } from './models/FixturePlayers_NoAutoPK';
export type { FixturePlayers_NoPK } from './models/FixturePlayers_NoPK';
export type { Fixtures } from './models/Fixtures';
export type { Fixtures_NoAutoPK } from './models/Fixtures_NoAutoPK';
export type { Fixtures_NoPK } from './models/Fixtures_NoPK';
export type { FixtureStaffs } from './models/FixtureStaffs';
export type { FixtureStaffs_NoAutoPK } from './models/FixtureStaffs_NoAutoPK';
export type { FixtureStaffs_NoPK } from './models/FixtureStaffs_NoPK';
export type { OffenceCodes } from './models/OffenceCodes';
export type { OffenceCodes_NoAutoPK } from './models/OffenceCodes_NoAutoPK';
export type { OffenceCodes_NoPK } from './models/OffenceCodes_NoPK';
export type { Officials } from './models/Officials';
export type { Officials_NoAutoPK } from './models/Officials_NoAutoPK';
export type { Officials_NoPK } from './models/Officials_NoPK';
export type { OfficialTypes } from './models/OfficialTypes';
export type { OfficialTypes_NoAutoPK } from './models/OfficialTypes_NoAutoPK';
export type { OfficialTypes_NoPK } from './models/OfficialTypes_NoPK';
export type { Seasons } from './models/Seasons';
export type { Seasons_NoAutoPK } from './models/Seasons_NoAutoPK';
export type { Seasons_NoPK } from './models/Seasons_NoPK';
export type { StaffTypes } from './models/StaffTypes';
export type { StaffTypes_NoAutoPK } from './models/StaffTypes_NoAutoPK';
export type { StaffTypes_NoPK } from './models/StaffTypes_NoPK';
export type { StageRulesets } from './models/StageRulesets';
export type { StageRulesets_NoAutoPK } from './models/StageRulesets_NoAutoPK';
export type { StageRulesets_NoPK } from './models/StageRulesets_NoPK';
export type { Stages } from './models/Stages';
export type { Stages_NoAutoPK } from './models/Stages_NoAutoPK';
export type { Stages_NoPK } from './models/Stages_NoPK';
export type { StageTeams } from './models/StageTeams';
export type { StageTeams_NoAutoPK } from './models/StageTeams_NoAutoPK';
export type { StageTeams_NoPK } from './models/StageTeams_NoPK';
export type { TeamFixtureResults } from './models/TeamFixtureResults';
export type { TeamFixtureResults_NoAutoPK } from './models/TeamFixtureResults_NoAutoPK';
export type { TeamFixtureResults_NoPK } from './models/TeamFixtureResults_NoPK';
export type { TeamPlayers } from './models/TeamPlayers';
export type { TeamPlayers_NoAutoPK } from './models/TeamPlayers_NoAutoPK';
export type { TeamPlayers_NoPK } from './models/TeamPlayers_NoPK';
export type { Teams } from './models/Teams';
export type { Teams_NoAutoPK } from './models/Teams_NoAutoPK';
export type { Teams_NoPK } from './models/Teams_NoPK';
export type { TeamStaffs } from './models/TeamStaffs';
export type { TeamStaffs_NoAutoPK } from './models/TeamStaffs_NoAutoPK';
export type { TeamStaffs_NoPK } from './models/TeamStaffs_NoPK';
export type { Users } from './models/Users';
export type { Users_NoAutoPK } from './models/Users_NoAutoPK';
export type { Users_NoPK } from './models/Users_NoPK';
export type { Venues } from './models/Venues';
export type { Venues_NoAutoPK } from './models/Venues_NoAutoPK';
export type { Venues_NoPK } from './models/Venues_NoPK';
export type { VenueTypes } from './models/VenueTypes';
export type { VenueTypes_NoAutoPK } from './models/VenueTypes_NoAutoPK';
export type { VenueTypes_NoPK } from './models/VenueTypes_NoPK';

export { AdjustmentTypesService } from './services/AdjustmentTypesService';
export { AssociationsService } from './services/AssociationsService';
export { AssociationStaffsService } from './services/AssociationStaffsService';
export { AssociationStaffTypesService } from './services/AssociationStaffTypesService';
export { AssociationTeamsService } from './services/AssociationTeamsService';
export { ClubsService } from './services/ClubsService';
export { CompetitionsService } from './services/CompetitionsService';
export { CompetitionSeasonsService } from './services/CompetitionSeasonsService';
export { CompetitionTypesService } from './services/CompetitionTypesService';
export { FixtureEventsService } from './services/FixtureEventsService';
export { FixtureOfficialAppointmentsService } from './services/FixtureOfficialAppointmentsService';
export { FixturePlayersService } from './services/FixturePlayersService';
export { FixturesService } from './services/FixturesService';
export { FixtureStaffsService } from './services/FixtureStaffsService';
export { OffenceCodesService } from './services/OffenceCodesService';
export { OfficialsService } from './services/OfficialsService';
export { OfficialTypesService } from './services/OfficialTypesService';
export { SeasonsService } from './services/SeasonsService';
export { StaffTypesService } from './services/StaffTypesService';
export { StageRulesetsService } from './services/StageRulesetsService';
export { StagesService } from './services/StagesService';
export { StageTeamsService } from './services/StageTeamsService';
export { TeamFixtureResultsService } from './services/TeamFixtureResultsService';
export { TeamPlayersService } from './services/TeamPlayersService';
export { TeamsService } from './services/TeamsService';
export { TeamStaffsService } from './services/TeamStaffsService';
export { UsersService } from './services/UsersService';
export { VenuesService } from './services/VenuesService';
export { VenueTypesService } from './services/VenueTypesService';
