name: PR

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    environment: Dev
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: 'Generate tfvars file'
        shell: bash
        run: |
          npm install
          npm run build