name: Release (Live)

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: Live
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_DUNE_07EE4D803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "" 
          output_location: "out" 
        env:
          B2C_CLIENT_ID: 017c1045-b0db-4e87-bc13-87d68dce0185
          B2C_CLIENT_SECRET: ${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}
          NEXT_PUBLIC_MEDIA_ENDPOINT: ${{ vars.NEXT_PUBLIC_MEDIA_ENDPOINT }}
          NEXT_PUBLIC_DOMAIN: ${{ vars.NEXT_PUBLIC_DOMAIN }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Environment Variables in Staging
        shell: bash
        env:
          AZURE_AD_B2C_CLIENT_SECRET: ${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}
          NEXT_PUBLIC_MEDIA_ENDPOINT: ${{ vars.NEXT_PUBLIC_MEDIA_ENDPOINT }}
          NEXT_PUBLIC_DOMAIN: ${{ vars.NEXT_PUBLIC_DOMAIN }}
        run: |
          az staticwebapp appsettings set \
            --name "squaregrid" \
            --resource-group "Landing-Zones-Default" \
            --setting-names \
            B2C_CLIENT_ID=017c1045-b0db-4e87-bc13-87d68dce0185 \
            B2C_CLIENT_SECRET=$AZURE_AD_B2C_CLIENT_SECRET \
            NEXT_PUBLIC_MEDIA_ENDPOINT=$NEXT_PUBLIC_MEDIA_ENDPOINT \
            NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN

