name: Release (Dev)

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: Dev
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_DUNE_07EE4D803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "" 
          output_location: "" 
          deployment_environment: "Dev"
        env:
          NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME: ourgameauth
          NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID: 017c1045-b0db-4e87-bc13-87d68dce0185
          AZURE_AD_B2C_CLIENT_SECRET: ${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}
          NEXT_PUBLIC_AZURE_AD_B2C_PRIMARY_USER_FLOW: B2C_1_SUSI
          AZURE_AD_B2C_SCOPES: "offline_access openid https://ourgameauth.onmicrosoft.com/sg-api/app.read https://ourgameauth.onmicrosoft.com/sg-api/app.write"
          NEXTAUTH_SECRET: ${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          AZURE_AD_B2C_ENDPOINT: https://ourgameauth.b2clogin.com/ourgameauth.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/
          NEXT_PUBLIC_MEDIA_ENDPOINT: ${{ vars.NEXT_PUBLIC_MEDIA_ENDPOINT }}
          NEXT_PUBLIC_DOMAIN: ${{ vars.NEXT_PUBLIC_DOMAIN }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Environment Variables in Staging
        shell: bash
        env:
          AZURE_AD_B2C_CLIENT_SECRET: ${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.AZURE_AD_B2C_CLIENT_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          NEXT_PUBLIC_MEDIA_ENDPOINT: ${{ vars.NEXT_PUBLIC_MEDIA_ENDPOINT }}
          NEXT_PUBLIC_DOMAIN: ${{ vars.NEXT_PUBLIC_DOMAIN }}
        run: |
          az staticwebapp appsettings set \
            --name "squaregrid" \
            --resource-group "Landing-Zones-Default" \
            --environment-name Dev \
            --setting-names NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME=ourgameauth \
            NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID=017c1045-b0db-4e87-bc13-87d68dce0185 \
            AZURE_AD_B2C_CLIENT_SECRET=$AZURE_AD_B2C_CLIENT_SECRET \
            NEXT_PUBLIC_AZURE_AD_B2C_PRIMARY_USER_FLOW=B2C_1_SUSI \
            AZURE_AD_B2C_SCOPES="offline_access openid https://ourgameauth.onmicrosoft.com/sg-api/app.read https://ourgameauth.onmicrosoft.com/sg-api/app.write" \
            NEXTAUTH_SECRET=$AZURE_AD_B2C_CLIENT_SECRET \
            NEXTAUTH_URL=$NEXTAUTH_URL \
            API_ENDPOINT=$API_ENDPOINT \
            AZURE_AD_B2C_ENDPOINT=https://ourgameauth.b2clogin.com/ourgameauth.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/ \
            NEXT_PUBLIC_MEDIA_ENDPOINT=$NEXT_PUBLIC_MEDIA_ENDPOINT \
            NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN

